name: Deploy React App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment for deployment'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - PROD

jobs:
  deploy:
    runs-on: self-hosted
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Consume Repository Secrets & Variables
        run: |
          echo "Consume Repository Secrets & Variables Started"
          echo "ENV=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
 
          if [ "$ENV" == "PROD" ]; then
            echo "DIRECTORY_PATH=${{ vars.PROD_DIRECTORY_PATH }}" >> $GITHUB_ENV
            echo "VITE_NODE_ENV=${{ secrets.PROD_VITE_NODE_ENV }}" > .env
            echo "VITE_APP_ID=${{ secrets.PROD_VITE_APP_ID }}" >> .env
            echo "VITE_APP_KEY=${{ secrets.PROD_VITE_APP_KEY }}" >> .env
            echo "VITE_API_URL=${{ secrets.PROD_VITE_API_URL }}" >> .env
          else
            echo "DIRECTORY_PATH=${{ vars.DEV_DIRECTORY_PATH }}" >> $GITHUB_ENV
            echo "VITE_NODE_ENV=${{ secrets.DEV_VITE_NODE_ENV }}" > .env
            echo "VITE_APP_ID=${{ secrets.DEV_VITE_APP_ID }}" >> .env
            echo "VITE_APP_KEY=${{ secrets.DEV_VITE_APP_KEY }}" >> .env
            echo "VITE_API_URL=${{ secrets.DEV_VITE_API_URL }}" >> .env
          fi
          
          echo "Consume Repository Secrets & Variables Completed"
      
      - name: Build the app
        run: |
          echo "Building app for environment: $ENV"
          npm run build --force

      - name: Move the build to the specified directory
        run: |
          echo "Moving build to directory: $DIRECTORY_PATH"
          mv dist $DIRECTORY_PATH

      - name: Run preview command
        run: |
          cd $DIRECTORY_PATH
          npm run preview

      - name: Clean up build directory
        run: |
          echo "Cleaning up build directory..."
          rm -rf $GITHUB_WORKSPACE/dist
