name: Deploy React App

on:
  push:
    branches:
      - development
      - workflow

  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment for deployment'
        required: true
        default: 'DEV'
        type: choice
        options:
          - DEV
          - PROD

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js v20.18.0
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Check Node.js version
        run: |
          node -v

      - name: Check npm version
        run: |
          npm -v

      - name: Consume Repository Secrets & Variables
        run: |
          echo "Consume Repository Secrets & Variables Started"
          echo "ENV=${{ github.event.inputs.environment || 'DEV' }}" >> $GITHUB_ENV
          if [ "$ENV" == "PROD" ]; then
            echo "DIRECTORY_PATH=${{ vars.PROD_DIRECTORY_PATH }}" >> $GITHUB_ENV
            echo "VITE_NODE_ENV=${{ secrets.PROD_VITE_NODE_ENV }}" > .env
            echo "VITE_APP_ID=${{ secrets.PROD_VITE_APP_ID }}" >> .env
            echo "VITE_APP_KEY=${{ secrets.PROD_VITE_APP_KEY }}" >> .env
            echo "VITE_API_URL=${{ secrets.PROD_VITE_API_URL }}" >> .env
          else
            echo "DIRECTORY_PATH=${{ vars.DEV_DIRECTORY_PATH }}" >> $GITHUB_ENV
            echo "VITE_NODE_ENV=${{ secrets.DEV_VITE_NODE_ENV }}" > .env
            echo "VITE_APP_ID=${{ secrets.DEV_VITE_APP_ID }}" >> .env
            echo "VITE_APP_KEY=${{ secrets.DEV_VITE_APP_KEY }}" >> .env
            echo "VITE_API_URL=${{ secrets.DEV_VITE_API_URL }}" >> .env
          fi
          echo "Consume Repository Secrets & Variables Completed"

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies with npm ci
        run: |
          echo "Installing dependencies with npm ci..."
          npm ci
          npm install --save-dev @types/react-dom  # Ensure react-dom types are installed

      - name: TypeScript Compile Check
        run: |
          echo "Running TypeScript compile check..."
          npx tsc --noEmit  # This will check for type errors without generating output files

      - name: Build the app
        run: |
          echo "Building app for environment: $ENV"
          npm run build --f

      - name: Move the build to the specified directory
        run: |
          echo "Moving build to directory: $DIRECTORY_PATH"
          mv dist/* $DIRECTORY_PATH

      - name: Run preview command
        run: |
          echo "Running preview command in directory: $DIRECTORY_PATH"
          cd $DIRECTORY_PATH
          npm run preview

  cleanup:
    runs-on: self-hosted
    needs: build  # Ensure this job runs after the build job completes
    steps:
      - name: Clean up build directory
        run: |
          echo "Cleaning up build directory..."
          rm -rf $GITHUB_WORKSPACE/dist
